### ISSUE TITLE
`[cardano-mint-burn primitive]` can't know who minted or burned an NFT

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/paima-engine#326]
Currently, the `cardano-mint-burn` only gives you `txId|metadata|assets` which is not enough to actually really do anything with this primitive. For example, for Tarochi, we want to detect who mints an NFT (so the game can react to it) and who burns an NFT (so the game can credit it to their account), but this primitive helps us with neither of these

At most you can partially work around this by adding a `cardano-delayed-asset` for the same policy ID you're minting with, but this has 3 problems:
1. It puts the complexity on the app-developer needlessly
2. I'm not sure if the order of the primitives is guaranteed (i.e. are we guaranteed the mint primitive updates the STF before the delayed asset primitive does?)
3. This only helps for the `mint` case, but doesn't help for the `burn` case

It looks like fixing this needs to start from an update to the Carp `asset/mint-burn-history` endpoint (which also doesn't return the information we need). I think the process to fix therefore goes as follows:

1. Update Carp. I think the easiest way to do this is to modify the `MintRangeController` so that after calling `mintBurnRange`/`mintBurnRangeByPolicyIds`, we make a follow-up query to get all UTXOs consumed & created for each txID found.  Then, we parse the `payload ` field of these utxos to to build a mapping of which addresses minted & burned
2. Update paima-engine to use this
3. Update the docs

Doing this will also help us get inline datum support for both this and the transfer CDE which is originally something we wanted

Careful: mints here should probably not cancel out. i.e. if they burn 100 coins and then mint 250, it should not cancel out to 150

**Comment by ecioppettini** [comment]
> At most you can partially work around this by adding a cardano-delayed-asset for the same policy ID you're minting with, but this has 3 problems:

You could also add the address in the metadata I suppose, although then it won't be generic/standard.

**Comment by SebastienGllmt** [comment]
Although adding the address in the metadata is possible, I feel like it's not a great solution because unlike the transfer case (where often it's impossible to know who is actually making the payment and so we give `metadata` as a fallback to `inputCredentials`), for minting it is very well defined exactly who burns and who mints because there is a concrete asset that is a UTXO owned by an address and so falling back to the metadata is still useful sometimes, but not usually needed
