### ISSUE TITLE
Wallet delegation cleanup

### ISSUE THREAD

**Issue by SebastienGllmt** [PaimaStudios/paima-engine#354]
Current, the wallet delegation system has 2 changes I think need to be made:

1. Currently `walletConnectCancelDelegation` requires a signature from the `to` address. I don't understand why this would be required (it would mean you can't undelegate your MetaMask wallet if you no longer have the private key for the burner wallet). Probably the interface should allow either no `to` address specified (clears all delegations), or specifying a `to` address to clear that specific delegation (but no signature required for the `to` address)

2. Remove the need for the `contract address` inside the Paima concise notation. I can't think of any reason why this was added. It wasn't in the specs either. I don't think this is required because
    1. The address is already included in the transaction as part of the [namespace](https://docs.paimastudios.com/home/read-write-L2-state/autosign#defining-your-namespace)
    2. The code we have now is wrong anyways because even if we needed this (which I don't think we do?), we should instead be using the namespace instead of the contract address

**Comment by acedward** [comment]
1. Cancel Delegations will be updated to `cancelDelegations   =   &wc|to?`  the optional `to` will define if one specific or all delegations will be removed. Cancel delegations will use the `from` of the message signer or its address if it has none.  `from = sender.from || sender` 

2. `contract_address` will be removed from paima-engine, and the helpers for building the signature plaintext.
